### ISSUE TITLE
Request: do not deselect after operation

### ISSUE THREAD

**Issue by kribjo** [Blossomforth/BlossomsPokemonGoManager#556]
Current behavior:
After an operation like Rename, the rows selection is reset to none.

Requested behavior:
After an operation, the selection should stay the same (NB: obviously, transferred Pokémon are no longer there/selected).

Example case:
User has a complex logic to select a large number of Pokémon for renaming and favorite-toggling. The logic is not easy to automate. With the current behavior it is necessary to do this complex and large selection process twice, since after doing the first operation the selection will be reset to none. With the suggested behavior the selection would stay and further operations on the same Pokémon group could be performed with ease.

Note: For consistency in the special case of the transfer operation, the Pokémon which were not able to be transferred (e.g. favorites) should still be selected after finishing the transfer operation.

**Comment by Wolfsblvt** [comment]
Yeah, already planned in my head xD
Will be done some time.

Sidenote: You haven't worked in some kind of customer support stuff, have you? Your issue text is like the best I could possibly imagine.

**Comment by kribjo** [comment]
Wolfsblvt: I've written and handled response to soooo many bug reports and feature requests... I try to do it as good as I can right from the start to avoid unnecessary energy spent on misunderstandings of vague phrasings, sometimes it works. :)
