### ISSUE TITLE
Some Pokémon are not evolvable (Babies, Gen2 evolutions)

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [Blossomforth/BlossomsPokemonGoManager#558]
This is probably an oversight.

**Comment by Wolfsblvt** [comment]
Baby Pokémon do not work either.
I am quite sure the evolution lines are missing in the API. We will check that.

**Comment by kribjo** [comment]
I would not expect Jynx to be evolvable to Blissey?!
Should the issue title read "Chansey is not evolvable to Blissey"?

**Comment by PolyglotOpenstreetmap** [comment]
So sorry, I'm tired most of the time. Apparently especially tired when I created this ticket.
