### ISSUE TITLE
Bug: Some species not displayed after batch rename

### ISSUE THREAD

**Issue by GlassToeStudio** [Blossomforth/BlossomsPokemonGoManager#560]
Version: BPGM_v0.1.7

Prereqs: 
- The pokemon in question had a nickname made in the game: 
- Batch renaming to %iv_att%-%iv_def%-%iv_stam% %iv_rating%%
- Don't know how many you need to rename at once, but I had many selected

EX:
- I have a perfect Eevee named PERFECTO.
- I named him while in the game.
- Batch renamed many pokemon including him.
- Once complete, I went to fix his name back to PERFECTO.
- I could not find him, 

Same happened with perfectly bad Bulbasaur (0-0-0). I had him named 0-0-0 RARE, that I changed in game. After batch renaming all my <50% pokemon, he did not show up,

**Comment by Dog-Pack** [comment]
Same for me I have about 50+ pokemon that  i can not see in game now and if i try renaming them again it just says 

[20:34:49]: Skipped renaming Pidgey, already named ""
[20:34:49]: Doing Rename 90 of 92
[20:34:49]: Skipped renaming Pinsir, already named ""
[20:34:49]: Doing Rename 91 of 92
[20:34:49]: Skipped renaming Clefairy, already named ""
[20:34:49]: Doing Rename 92 of 92
[20:34:49]: Skipped renaming Sentret, already named ""


Edit, Just sat down and renamed them all manually one at a time, and that got them back, looks like only batch rename is broken.

**Comment by kribjo** [comment]
Pokémon disappearing from the BPGM list may be related to issue https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/563 , where the list shows an "extra" pokémon which is not really there.
I am thinking that they might just be different aspects of some (in-application) list corruption.
