### ISSUE TITLE
Candy total not updating after transfer

### ISSUE THREAD

**Issue by bwheat** [Blossomforth/BlossomsPokemonGoManager#561]
I'm having an issue on the latest version 0.1.7 where I select and batch transfer pokemon, but it is not calculating the candy I have for that type in the column with the tool.

**Comment by Wolfsblvt** [comment]
Do you have a screenshot? What do you mean exactly? What candy total is not updating?

**Comment by bwheat** [comment]
Ok it took a few tries but I was able to reproduce it with spearows. Happened before with pidgeys, rattatas, caterpies. Here's a screenshot of before/after xfer and candies stay at 42
![postxfer](https://cloud.githubusercontent.com/assets/1081802/23317879/c74c968c-fa95-11e6-9161-d432dc57149e.PNG)
![prexfer](https://cloud.githubusercontent.com/assets/1081802/23317878/c74be106-fa95-11e6-8036-9e2875e537e1.PNG)

**Comment by marcelohenrique** [comment]
I can't reproduce this error. I tried with different pokemons and with same type, candies column is updating. I tested with released 0.1.7 and develop branch. I don't test with spearow.

**Comment by bwheat** [comment]
OK I think I have a more descriptive way to reproduce this issue. 
1) Select and transfer multiple pokemon of type A and notice the (Family) transfer in the console works as intended
2) select and transfer multiple pokemon of type B and notice the console doesn't include the same console log output with (Family) and doesn't update the candy total for pokemon B

Shown here before/after with xfering Ledybas (5 xfered from 75 to 80 candies) and then Hoothoots (7 transfered and candies stayed at 63) as A and B respectively 
![init](https://cloud.githubusercontent.com/assets/1081802/23368577/ef2fa2d0-fcd3-11e6-8777-7af3bb3d75e1.PNG)
![after](https://cloud.githubusercontent.com/assets/1081802/23368583/f2955140-fcd3-11e6-92e5-654ba69e6e7f.PNG)
