### ISSUE TITLE
"refresh list" not reliable

### ISSUE THREAD

**Issue by kribjo** [Blossomforth/BlossomsPokemonGoManager#563]
Version: 0.1.7

Behavior:
1. BPGM running on computer with a loaded list.
2. Evolve a Marill to Azumarill on other device (standard PoGo Android phone app).
3. Click "Refresh list" in BPGM.
BPGM lists both the (no longer existing) Marill and the (properly existing) Azumarill, both show with the same custom name and same IV. Row numbers are unique. Repeated "Refresh list" does not help.
![bug1](https://cloud.githubusercontent.com/assets/1691693/23352609/96214a82-fcc8-11e6-8889-9423720ebdcf.png)

Expected behavior:
BPGM should not list a non-existing Pokémon after "refresh list" is performed.

Workaround:
Shutting down BPGM and restarting it seems to fix the problem.

**Comment by darthvegas** [comment]
Not sure if this is related, but I'm seeing 'disappearing' pokemon after toggle favorite (in batch - haven't tried to recreate for single).  I'll take a set of pokemon, toggle the favorite indicator and some (not all) simply disappear.  Checking the app though shows they're still there.  Sorry - newb: should this be opened as a new defect?

**Comment by FernandoTBarros** [comment]
It is related. Not need to open a new issue
