### ISSUE TITLE
Release Zips Won't Download

### ISSUE THREAD

**Issue by StPatty33** [Blossomforth/BlossomsPokemonGoManager#569]
I know this isn't a code issue, but none of the official release zips will download (though the source code downloads fine).  Did the releases get blacklisted by github or the amazon cloud they use or something?  All of the official release links are broken for me, but the rest work fine.

**Comment by StPatty33** [comment]
This is what Chrome says when clicking any of the official release zips:
"This site can’t be reached
github-cloud.s3.amazonaws.com took too long to respond."

**Comment by Wolfsblvt** [comment]
There seems to be an issue with GitHubs file service I guess. Should be fixed soon hopefully?
It's not your fault, neither ours.

[Try this for the time being](http://pinkes-forum.de/download/BPGM_v0.1.7.zip).

**Comment by StPatty33** [comment]
Much appreciated--just wanted to make sure it wasn't specific to me.  It's odd that other zip downloads work, just not the actual release.  Anyway, thanks for all you do!  Look forward to grabbing the new version when it's back up!

**Comment by MGRza** [comment]
It did that with me last night too and this morning it is fine, was able to download it.

**Comment by Wolfsblvt** [comment]
There was a [Big outage at Amazon Web Services (AWS)](https://www.engadget.com/2017/02/28/amazon-aws-outage/) yesterday, which broke a big part of the internet actually.
Seems like GitHub is hosting their file uploads on AWS.

Issue is resolved now then.
