### ISSUE TITLE
Not a issue, more of a question

### ISSUE THREAD

**Issue by MGRza** [Blossomforth/BlossomsPokemonGoManager#570]
I apologize for creating this issue, wasnt sure where else to ask, I did read the FAQ but im still unsure as to one aspect, the Evolve feature, can we select a bunch of Pokemon and evolve them at once? Secondly if you activate a lucky egg before, will the double xp still count?

The game has been super laggy lately making the evolve for mass xp even worse than it already is so a tool to speed it up will be appreciated.

**Comment by Wolfsblvt** [comment]
Questions on GitHub are fine, as long as they are really needed. Don't want issue spam with dozens of questions, but as long as there is one every few issues popping up it's okay (:
The go-to place for questions would be our Discord server, btw. It is linked at the top.

And yes. You select a number of Pokémon, hit "Evolve" and then the tool evolves them one by one with a configured delay (default is random 3-12 seconds between each evolve) until it is finished.
And yeah, pop a lucky egg on your phone just before hitting Okay, and then you get double XP for every evolve (:

Do note that you can evolve at least 150 Pokémon with the tool in half an hour, and up to **600**. The random middle will be somewhere at 220-250 from my experience.

**Comment by MGRza** [comment]
Thanks so much, im new to this site, so not sure how everything works but will move mu future questions there, again thank you so much.
