### ISSUE TITLE
Warning from Niantec on my phone when opening app

### ISSUE THREAD

**Issue by boomschtick** [Blossomforth/BlossomsPokemonGoManager#577]
![warning](https://cloud.githubusercontent.com/assets/1853797/23736284/95f92b92-0448-11e7-9618-3fe3e10cb209.png)

I got this error today when opening the app.  Blossoms is the ONLY third party app that I use, so the behavior would have to have been flagged from whatever it is doing on the API.

I REALLY hope that I don't have to stop using it.  I don't relish the though of managing over 600 pokemon from the game interface!

**Comment by Parisian17** [comment]
I received the same warning... :-(

**Comment by LeonCheong** [comment]
Are you a GPS spoofer? Do you use any other software that teleport to other location?

**Comment by boomschtick** [comment]
Not once... never.  I think spoofing is cheating.  I think Blossoms is just management made simpler.  

Blossoms is the ONLY program that I have allowed to login with my google creds.

**Comment by gsziklai** [comment]
No, accessing Niantic servers with non-Niantic-sanctioned applications can get you this.
I got the same warning, and I never messed with my GPS. And never used Bossom for mass evolve or dust, either. 
I used only for managing and mass rename.
I have a PTC acc, changed the passwd, and never logged in again with anything but the official app: but the warning just wont go away.

**Comment by schagnon** [comment]
So wish we can tell niantic  that blossom would shut off the ability to evolve.   Losing the management ability is going to kill a bit of enjoyment of this game. While adding hours of doing silly tasks like determining which Pokémon to transfer.

**Comment by teamlowkey** [comment]
Same, I hadn't tried using BPGM for the last couple days since it wouldn't log in. I tried to use it again today, it again failed to log in (gave it 3 tries), and then the next time PoGo crashed, I got this warning on restart. And this warning again when it crashed five minutes later.

**Comment by jonmabbutt** [comment]
I got the same warning and this is the only app I used that breached TOS

**Comment by macinmn** [comment]
a great way to start killing off a game from your more enthused portion of audience...  they must only want mindless casual players

**Comment by notoriouspeb** [comment]
used often. no warning fwiw

**Comment by FernandoTBarros** [comment]
Some guys are receiving this warning and this may be related to the legacy login (0.45) that was discontinued by Niantic since last forced update (0.57.4)
The only way to log in now is using a hashkey but we can't guarantee that this is completely safe either.
