### ISSUE TITLE
Question:  Is this project dead?

### ISSUE THREAD

**Issue by boomschtick** [Blossomforth/BlossomsPokemonGoManager#580]
I see there is only one commit to master in almost 30 days.  I'm no developer, so I don't know, but I assume that means that not much is being done.  Has Niantec's constant API changes made it so that it's not worth trying to keep up?

I'd just like to know so that I don't keep checking this site for a new release that supports the new API.

Thanks!

**Comment by Redarion** [comment]
Actually there is an hotfix in discord channel #announcement. Give it a try if is what you are looking for.

**Comment by thisischrys** [comment]
Sidenote: The free APIs are now all dead, only the paid hashing APIs can be used

**Comment by pbhound** [comment]
where does one purchase a paid API?

**Comment by vuice** [comment]
@pbhound https://talk.pogodev.org/d/55-api-hashing-service-f-a-q

**Comment by FernandoTBarros** [comment]
It's not dead. We are preparing an official release here soon.
